"""Core Phase 1 data models and persistence for Arkzen."""

from .models import (
    AcquisitionCacheEntry,
    AcquisitionCheckpoint,
    AcquisitionRun,
    Evidence,
    EvidenceReview,
    EvidenceReviewStatus,
    Qualification,
    QualificationStatus,
    WatchProfile,
)
from .persistence import SQLiteRepository
from .qualification import QualificationError, evaluate_evidence
from .intent_capture import create_watch_profile_from_input, parse_terms
from .monitoring import (
    AcquisitionRunResult,
    CandidateValidationError,
    NormalizedCandidate,
    ProviderCapabilities,
    ProviderHealth,
    PostSource,
    RawPost,
    SignalMonitor,
    TwscrapeAccount,
    TwscrapePostSource,
    build_search_query,
    find_match_reason,
    find_matched_patterns,
    load_twscrape_accounts,
    freshness_rejection,
    normalize_candidate,
)

__all__ = [
    "Evidence",
    "EvidenceReview",
    "EvidenceReviewStatus",
    "AcquisitionCacheEntry",
    "AcquisitionCheckpoint",
    "AcquisitionRun",
    "Qualification",
    "QualificationStatus",
    "AcquisitionRunResult",
    "CandidateValidationError",
    "NormalizedCandidate",
    "ProviderCapabilities",
    "ProviderHealth",
    "PostSource",
    "RawPost",
    "SignalMonitor",
    "SQLiteRepository",
    "TwscrapeAccount",
    "TwscrapePostSource",
    "WatchProfile",
    "build_search_query",
    "create_watch_profile_from_input",
    "find_match_reason",
    "find_matched_patterns",
    "load_twscrape_accounts",
    "freshness_rejection",
    "normalize_candidate",
    "parse_terms",
    "QualificationError",
    "evaluate_evidence",
]
